name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd server
      - run: npx prisma db push --schema prisma/schema.prisma
      - run: npx prisma generate --schema prisma/schema.prisma
      - run: npm i
      - run: cd ../client
      - run: npm i
      - run: npm run build
      - run: cd ../
      - run: pm2 restart 0
      - run: pm2 save
      - run: sudo service nginx restart
