name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- run: prisma db push --schema prisma/schema.prisma
      #- run: prisma generate --schema prisma/schema.prisma
      - run: |
          cd server
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          npm i
          cd ../client
          npm i
          npm run build
          cd ../server
          npm run db:push
          cd ../
          pm2 restart 0
          pm2 save
          sudo service nginx restart
